from pydantic import BaseModel
from typing import Any, Optional


class DadataAddress(BaseModel):
    source: Optional[str] = None
    result: Optional[str] = None
    postal_code: Optional[str] = None
    country: Optional[str] = None
    country_iso_code: Optional[str] = None
    federal_district: Optional[str] = None
    region_fias_id: Optional[str] = None
    region_kladr_id: Optional[str] = None
    region_iso_code: Optional[str] = None
    region_with_type: Optional[str] = None
    region_type: Optional[str] = None
    region_type_full: Optional[str] = None
    region: Optional[str] = None
    area_fias_id: Optional[str] = None
    area_kladr_id: Optional[str] = None
    area_with_type: Optional[str] = None
    area_type: Optional[str] = None
    area_type_full: Optional[str] = None
    area: Optional[str] = None
    city_fias_id: Optional[str] = None
    city_kladr_id: Optional[str] = None
    city_with_type: Optional[str] = None
    city_type: Optional[str] = None
    city_type_full: Optional[str] = None
    city: Optional[str] = None
    city_area: Optional[str] = None
    city_district_fias_id: Optional[str] = None
    city_district_kladr_id: Optional[str] = None
    city_district_with_type: Optional[str] = None
    city_district_type: Optional[str] = None
    city_district_type_full: Optional[str] = None
    city_district: Optional[str] = None
    settlement_fias_id: Optional[str] = None
    settlement_kladr_id: Optional[str] = None
    settlement_with_type: Optional[str] = None
    settlement_type: Optional[str] = None
    settlement_type_full: Optional[str] = None
    settlement: Optional[str] = None
    street_fias_id: Optional[str] = None
    street_kladr_id: Optional[str] = None
    street_with_type: Optional[str] = None
    street_type: Optional[str] = None
    street_type_full: Optional[str] = None
    street: Optional[str] = None
    stead_fias_id: Optional[str] = None
    stead_kladr_id: Optional[str] = None
    stead_cadnum: Optional[str] = None
    stead_type: Optional[str] = None
    stead_type_full: Optional[str] = None
    stead: Optional[str] = None
    house_fias_id: Optional[str] = None
    house_kladr_id: Optional[str] = None
    house_cadnum: Optional[str] = None
    house_type: Optional[str] = None
    house_type_full: Optional[str] = None
    house: Optional[str] = None
    block_type: Optional[str] = None
    block_type_full: Optional[str] = None
    block: Optional[str] = None
    entrance: Optional[str] = None
    floor: Optional[str] = None
    flat_fias_id: Optional[str] = None
    flat_cadnum: Optional[str] = None
    flat_type: Optional[str] = None
    flat_type_full: Optional[str] = None
    flat: Optional[str] = None
    flat_area: Optional[str] = None
    square_meter_price: Optional[str] = None
    flat_price: Optional[str] = None
    postal_box: Optional[str] = None
    fias_id: Optional[str] = None
    fias_code: Optional[str] = None
    fias_level: Optional[int] = None
    fias_actuality_state: Optional[str] = None
    kladr_id: Optional[str] = None
    capital_marker: Optional[str] = None
    okato: Optional[str] = None
    oktmo: Optional[str] = None
    tax_office: Optional[str] = None
    tax_office_legal: Optional[str] = None
    timezone: Optional[str] = None
    geo_lat: Optional[str] = None
    geo_lon: Optional[str] = None
    beltway_hit: Optional[str] = None
    beltway_distance: Optional[str] = None
    qc_geo: Optional[int] = None
    qc_complete: Optional[int] = None
    qc_house: Optional[int] = None
    qc: Optional[int] = None
    unparsed_parts: Optional[str] = None
    metro: Optional[list[dict[str, Any]]] = None


class DadataPartyData(BaseModel):
    address: Optional[DadataAddress] = None
    emails: Optional[list[dict[str, Any]]] = None
    employee_count: Optional[int] = None
    finance: Optional[dict[str, Any]] = None
    fio: Optional[dict[str, Any]] = None
    hid: Optional[str] = None
    inn: Optional[str] = None
    licenses: Optional[list[dict[str, Any]]] = None
    name: Optional[dict[str, Any]] = None
    ogrn: Optional[str] = None
    ogrn_date: Optional[int] = None
    okato: Optional[str] = None
    okfs: Optional[str] = None
    okogu: Optional[str] = None
    okpo: Optional[str] = None
    oktmo: Optional[str] = None
    okved: Optional[str] = None
    okved_type: Optional[str] = None
    okveds: Optional[list[dict[str, Any]]] = None
    opf: Optional[dict[str, Any]] = None
    phones: Optional[list[dict[str, Any]]] = None
    qc: Optional[str] = None
    state: Optional[dict[str, Any]] = None
    type: Optional[str] = None
    value: Optional[str] = None
